bekk/bekk-blogg

- web/app/features/teaser/TeaserPage.tsx
- web/app/hooks/useClientSideOnly.ts
- web/app/portable-text/CodeBlock.tsx
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Bug-i-kodeeditor-Object-object-14c6bd30854180e88278d40c2ee931e8)
🐛 Type oppgave: Bug
🥅 Mål med PRen: Fikse feil i kodeeditor som blir [Object object]...
🆕 Endring: Kun rendre syntaxhighlighteren på klientsiden. På server rendrere vi bare en <code />-tag
- Flyttet ut `useClientSideOnly()`-hooken i en egen fil, da jeg trengte den her.
> Nytt forsøk på å fikse kodeeditor 🤞 

- web/app/features/post-preview/PostPreview.tsx
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Vise-lengde-p-podcast-p-lukeside-1526bd30854180ccaeb7dea8d5ea4a02?pvs=4)
🛠️  FIKS
🥅 Mål med PRen: Vise reading time på podcaster 
- Måtte bare endre sjekken på når man skulle vise reading time 
Har sjekka gjennom artiklene fra 2024 og 2023 og det ser ut til å funke, men gjerne sjekk litt andre steder også
> add reading time to podcasts

- web/utils/sanity/queries/postQueries.ts
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Ikke-vise-artikler-som-ikke-har-noe-content-1526bd30854180608acddc272eed78c9?pvs=4)
🛠️  FIKS
🥅 Mål med PRen: Fjerne artikler som ikke har noe content 
Noen av artiklene som ligger ute har null content som f.eks. [denne](https://www.bekk.christmas/post/2023/09/ux-is-going-awry-what-if-we-blew-it)
- Endret groq-kallet til å sjekke om podcastlength er ulik null eller wordcount er større enn null for å filtrere bort disse
Har sjekka at alle artiklene fra 2024 (som har kommet ut) fortsatt vises, samt alle fra 2023 som ikke har null content, men gjerne sjekk litt til hvis dere gidder.
> remove articles without content

- web/app/features/post-preview/PostPreview.tsx
- web/utils/sanity/queries/postQueries.ts
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Legge-til-hva-slags-type-artikkel-det-er-p-lukesiden-1526bd30854180639854cdda36142dd5?pvs=4)
💄 STYLING
🥅 Mål med PRen: Legge til hvilken type artikkel det er på preview av artikkel
- Lagt til type i sanity-kallet så vi kan hente ut hva slags artikkel det er (video vs artikkel vs podcast)
> add article type to luke preview

- web/app/features/article/Article.tsx
- web/app/styles/main.css
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Aligne-meta-og-content-p-artikkelside-1526bd3085418093a3abecce07771fa6?pvs=4)
💄 STYLING
🥅 Mål med PRen: Aligne meta og artikkelcontent 
- Litt hacky løsning med å fjerne padding fra ingress eller content på første p-taggen innenfor den div-en 
FØR 
ETTER
> align meta and content

- web/app/routes/forfatter.$name.tsx
- web/app/routes/kategori.$tag.tsx
- web/app/routes/post.$year.$date.$slug.tsx
- web/app/routes/post.$year.$date.tsx
- web/app/routes/post.$year.tsx
Denne PRen legger til "no-cache, no-store" cache-control header direktiver på alle feilsituasjoner. Det vil si – hvis man får en 404-feil, så cacher man ikke den feilen, men sjekker på nytt igjen hver gang. I dag setter vi bare default headerne om man får en feil, som fører til at feil caches i en time 😬 
Om caching headers og caching-direktiver er litt kryptisk for deg, så forklarer Chat GPT forskjellen på de to forskjellige direktivene slik:
> no-store og no-cache i Cache-Control-headeren styrer hvordan ressurser håndteres i nettlesere og mellomlagre. Med no-store instrueres klienter og mellomlagre om aldri å lagre dataen, verken i minnet eller på disk. Dette sikrer at sensitive data, som brukerinformasjon eller betalingstransaksjoner, alltid hentes direkte fra serveren uten risiko for …
> Ikke cache feilsituasjoner

- web/utils/sanity/config.ts
- web/utils/sanity/loadQueryOptions.server.ts
Ser ut til at preview mode ofte blir slått på i prod selv om man ikke har noen cookies. Jeg tror det kanskje er fordi sanity-klienten ikke får inn den informasjonen den trenger i disse kontekstene, men er usikker.
Legger derfor på litt ekstra "skallsikring", slik at det skal være nærmere umulig å få opp preview mode om man ikke skal. Men må debugge litt, så derfor er det litt console logs med i PRen. Disse blir tatt vekk før merge.
> Slå av preview mode om cookie ikke er satt

- web/app/routes/post.$year.tsx
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Planke-i-toppen-1576bd3085418051b66cea89613554d0?pvs=4)
🐛 Type oppgave: bug
🥅 Mål med PRen: Feil bakgrunn ble brukt på artikkelside, så den store planken kom i toppen
- Endret bakgrunn til å kun bruke brick wall (uten wooden plank)
**Før:**
**Etter:**
> 🐛 Bruke riktig bakgrunn på artikkelside

- web/app/root.tsx
- web/app/routes/resource.preview.tsx
- web/utils/sanity/loadQueryOptions.server.ts
Så det viser seg at når vi er i Sanity preview mode i prod, så lastes ikke VisualEditing komponenten. Det kommer mest sannsynlig fra at vi returnerer ganske harde cache headers på rotnivå uansett.
Denne PRen returnerer "riktige" cache headers basert på om man er i preview modus eller ei. Også legger jeg på litt logging for å dobbeltsjekke at dette stemmer.
> Fiks preview igjen

- web/app/routes/sitemap.xml.tsx
Google Search Console klager over at vi mangler et namespace. Vi hadde forsåvidt et namespace, men det så litt feil ut.
> Bruk riktig namespace

- web/app/hooks/useBreadcrumbs.ts
Ahh skulle testa enda litt bedre.
Når man går til en forfatter som ikke finnes, så brekker prod fordi man prøver å lese fra match som ikke finnes. 😬 Denne PRen legger til en if-sjekk for nettopp det.
> Ikke les fra forfatter om man ikke finner den

- sanity/package-lock.json
- sanity/package.json
- sanity/sanity.config.ts
- sanity/schemas/objects/portableText.tsx
- web/app/components/ui/table.tsx
- web/app/lib/utils.ts
- web/app/portable-text/Components.tsx
- web/app/portable-text/TableBlock.tsx
- web/app/styles/fonts.css
- web/components.json
- web/package-lock.json
- web/package.json
- web/tailwind.config.ts
Preben ville gjerne ha tabeller for en av artiklene sine. Så da legger vi til tabeller!
Sanity har sin egen tabell-plugin, og så brukte jeg shadcn til å rendre tabeller
> Legg til støtte for tabeller

- web/app/features/article/LikeContent.tsx
Vi observerte [en feil](https://vercel.com/bekk/bekk-blogg/logs?levels=error&selectedLogId=tpcln-1734454704465-478520f9d62b) når man prøver å preview noe før man har valgt språk. Det vil ikke være en bug i faktisk prod, men det vil hindre folk i å previewe før man har valgt språk.
- Om man ikke har valgt språk, default til norsk (bokmål)
> Legg til fallback-språk

- web/app/routes/category.$tag.tsx
- web/app/routes/kategori.$tag.tsx
- web/app/routes/post.$year.$date.$slug.tsx
Når man prøver å redirecte til en side med æ, ø eller å i navnet, så feiler Vercel, siden det ikke er lov å sende ikke-ascii bokstaver som headers.
Når man redirecter får man tilbake en 301 eller 302 HTTP status-kode, med en `Location` header, som inneholder hvor man skal bli videresendt til. Det er altså denne som ikke kan inneholde æ-er, ø-er eller å-er. 
- Wrap slugs og kategorinavn med "encodeURIComponent", som gjør om æøå til litt mer URL-vennlige strings.
- Når man henter ut slugs og kategorinavn, husk å kalle den motsatte "decodeURIComponent" funksjonen for å få tilbake spesialtegnene.
> Fiks redirect feil

- web/app/portable-text/CodeBlock.tsx
Språket "hcl" var ikke lagt til som et gyldig språk for refractor (kodehighlighteren vår), så da kræsjer https://www.bekk.christmas/post/2019/20/terraforming-christmas-cards. Ikkje bra.
Heldigvis støtter refractor hcl!
I tillegg så så jeg at vi egentlig støtter flere av de språkene som er lagt til på "ikke-støtta"-listen jeg laget i forrige PR – bare at de er skrevet med feil casing. Denne PRen tar derfor og endrer språket til lowercase-versjonen av hva enn vi får inn. Dette gjør at et par flere artikler får den kodehighlighten vi ønsker.
- Legg til støtte for hcl
- Lowercase alle språk vi får inn, så vi kan highlighte kode i et par flere innholdsartikler.
Du kan se at siden ikke kræsjer lenger her: …
> Legg til HCL som støttet språk og støtt uppercase-språk

- web/app/routes/post.$year.$date.$slug.tsx
Filtrer ut innlegg som ikke skal være tilgjengelige enda i som forslag i relaterte innlegg. 
Gjør det på klienten, da jeg ikke fikk det til på server som en litt temp. fix, da det ser noe rart ut å anbefale innlegg som ikke er tilgjengelige enda.
- Lagt til filter på alle items som vises i relaterte innlegg
> Filter out unavailable posts

- web/app/components/Search.tsx
- web/app/features/article/RelatedPostLayout.tsx
- web/app/features/header/Header.tsx
- web/app/hooks/useAlgolia.ts
- web/app/root.tsx
- web/app/routes/post.$year.$date.$slug.tsx
- web/utils/security.ts
Gikk gjennom søkeimplementasjonen, og rettet opp noen greier her og der.
- La til noen manglende domener i CSPen vår
- Fiksa noen console-feil
- La til noen future flags for instant search APIet, så det ikke klager under utvikling
- Laget to hooks – useAlgoliaConfig og useAlgoliaClient – og brukte dem rundt om der det var behov
- Fikset en bug med formatteringen av forfattere på relatert innhold
- Endret overskriften på relatert innhold fra "Relaterte artikler" til "Relatert innhold"
> Fiks noen søkebugs

- web/app/components/RelatedLink.tsx
Medium har begynt å blokkere URL-previewen vår – opengraph.ninja (laget av undertegnede) – fra å hente previews av artikler. Det er jo ikke helt prima.
Det som er litt kjipt er at i de tilfellene, så viser vi aldri lenken – vi viser bare at det ikke fungerte! Så det denne PRen gjør er å vise frem det vi vet fra URLen, og beholde lenken – bare uten fancy preview.
> Vis en enklere versjon av URLen om opengraph.ninja feiler

- sanity/schemas/documents/post.ts
Det er et par felter i Sanity som vi ikke egentlig bruker, eller trenger, på den nye siden. Denne PRen rydder opp i det, og flytter språk lenger opp (siden det er påkrevd)
- Skjul og depreker bilde-kilde (last heller opp)
- Skjul og depreker "vis kun på forside" (støttes ikke lenger i koden)
- Flytt språk opp
- Gi språk en defaultverdi av bokmål.
> Rydde opp litt i Sanity-innlegg

- web/app/features/article/Article.tsx
- web/app/portable-text/ImageBlock.tsx
I dag så viser vi det samme bildet uansett hva slags enhet du har. Men takket være `srcset` attributten til bilder, så kan man faktisk gi forskjellige bilder basert på hvilken størrelse devicen din har!
Denne PRen (automagisk generert av AI) legger til forskjellige størrelser på bildene, slik at man ikke laster ned mer enn man trenger.
Test gjerne at bilder ser bra ut – både cover image, men også bilder i artikler.
> Optimaliser bilder med srcset

- web/app/portable-text/ImageBlock.tsx
Fikser en bug i safari hvor tekst under en ImageBlock fløt over i bilde-caption
Før: 
Etter:
> Gjør om figure i ImageBlock til en inline-block

- web/app/components/Search.tsx
- web/app/features/calendar/CalendarWithDoors.tsx
- web/app/features/header/Header.tsx
På søkefeltkomponenten
- Filtrerer ut søketreff som er frem i tid, for å unngå 404
- Økt z-index for å vise søkeresultatet over kalendersiden, og litt styling på borders og hovereffekt
På kalendersiden:
- Lagt til søkefeltet på skjermer > 1130px. For skjermer under den størrelsen skal det vises i headeren. Det fikser jeg i egen PR.
Søkefelt på kalendersiden
Hover-effekt:
> Søkefelt på kalendersiden (kun desktop)

- web/app/components/Search.tsx
- web/app/routes/post.$year.tsx
- web/playwright.config.ts
- web/tests/home.spec.ts
Søkefelt på mobil!
- Lagt til en prop på inputfelt som bestemmer om det skal være transparent eller ikke
- På små skjermer (opp til 2lg) viser søkefeltet i toppen, ellers viser det inni "huset"
Ting som burde gjøres, men som jeg ikke tar i denne PRen:
- Forstørrelsesglassikon til høyre inni søkefeltet
- Når man trykker escape eller inputfeltet mister fokus, burde resultatene skjules
- Når man trykker pil ned eller tab burde lenkene highlightes og kunne velges med enter
> Legg til søkefelt på kalendersiden på mobil

- web/app/components/Search.tsx
Når man klikker utenfor søkeresultatet, burde resultatet skjules. Spesielt på mobil er dette relevant, for ellers må man viske ut det man har skrevet for å kunne trykke på luke nr. 1. 
Et lite issue her at man må trykke escape to ganger (første gang fjerner man bare focus fra inputfeltet, og andre gang blir trykket registrert). Usikker på hvorfor, men leste på stackoverflow at det var en bug i chromium (som er rart, for jeg bruker jo supreme firefox..)
- Lagt til event listeners for mouseDown og keyUp, som setter `showResults` til false og skjuler resultatene
> Legg til event listeners for escape press og klikk utenfor søkeresultat
