bekk/bekk-blogg

web/app/routes/post.$year.$date.$slug.tsx
Denne PRen fikser en bug som gjør at preview ikke funker som det skal. Grunnen til det er at vi cacher hardt, også når man er i preview. Det kan føre til litt trøbbel. Så istedenfor å cache så hardt, drar vi ned cachetiden en del, samt setter "ikke cache meg" headers hvis man er i preview.
=> Bare cache om man ikke er i preview

web/app/routes/post.$year.$date.$slug.tsx
Sånn går det når produktledere koder. Denne fikser en 500 feil på alle artikkelsider i prod 😬
=> Hotfix tok ned prod

web/app/features/article/Article.tsx, web/app/features/post-preview/PostPreview.tsx
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Zaigo-bug-14a6bd30854180a0be2df2014c62449e?pvs=4)
🐛 Type oppgave: _bug_
🥅 Mål med PRen: Fikset zaigo bug
🆕 Endring: Lagt på overflow-auto på tittelen 
_Ved frontendendringer legg ved bilde av før og etter._
**Før:**
**Etter:**
=> fix zaigo bug

README.md
Legger til endel nyttige lenker i readme-en, så vi har dem dokumentert et sted.
=> Legg til nyttige lenker i README

web/app/root.tsx, web/package-lock.json, web/package.json, web/utils/security.ts
Denne PRen legger til tracking av hvor rask siden vår er på Vercel.
=> Legg til speed insights

web/app/features/error-boundary/ErrorPage.tsx, web/app/features/header/Header.tsx, web/app/features/pagination/Pagination.tsx, web/app/features/post-preview/PostPreview.tsx, web/app/root.tsx, web/app/routes/arkiv.tsx, web/app/routes/forfatter.$name.tsx, web/app/routes/kategori.$tag.tsx, web/app/routes/kategori.tsx, web/app/routes/post.$year.$date.$slug.tsx, web/app/routes/post.$year.$date.tsx, web/app/routes/post.$year.tsx, web/app/styles/backgrounds.css, web/utils/headers.ts, web/utils/sanity/queries/postQueries.ts, web/utils/sanity/types/sanity.types.ts
Jeg lover. Jeg skulle bare fikse caching. Caching-headerne fungerte ikke helt optimalt fordi headers-funksjonen per route ikke blir kalt – det er headers-funksjonen på nivået hvor ErrorBoundary-komponenten som rendres som kalles.
For å fikse det, måtte jeg legge til en ErrorBoundary komponent per route. Men det førte til at "isError" på toppnivå alltid ble false (det var jo ingen feil "der oppe"). Og det brakk bakgrunnene våre.
SÅ jeg satt meg ned og skrev om måten vi gjør layouts på, til en litt "riktigere" måte der hver route blir ansvarlig for sin egen layout.
Også siden jeg jobbet meg gjennom halve kodebasen, så la jeg merke til at vi listet opp tomme kategorier. Så fiksa det i samme slengen. Også la jeg merke til at den "entry"-animasjonen på brev (PostPreview) var kjempe-buggy når …
=> Jeg skulle bare fikse caching

web/utils/sanity/loadQueryOptions.server.ts
Ref #257 , så la vi til litt debug-logging for å se om vi fant ut av problemene. Heldigvis fiksa forrige PR biffen, som gjør at vi kan fjerne denne loggingen igjen.
=> Fjern debug-logging

web/app/routes/post.$year.tsx
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Legge-inn-scroll-p-hovedside-1546bd308541801fa078fdd261875b68?pvs=4)
🐛 BUG
🥅 Mål med PRen: Legge til muligheten for å scrolle på kalenderside
=> La til mulighet for å scrolle på kalenderside på stor skjerm

web/app/routes/post.$year.$date.$slug.tsx, web/utils/sanity/sanity.server.ts
Ser ut til at det ikke fubker å stemme i prod. Denne pren prøver å fikse det.
=> Ikke bruk cdn på write-klienten

sanity/sanity.config.ts, sanity/schema.json, sanity/schemas/documents/author.ts, sanity/schemas/objects/socialMediaLink.tsx, web/.eslintrc.cjs, web/app/features/article/AudioPlayer.tsx, web/app/features/article/BekkLogo.tsx, web/app/features/article/DayNavigation.tsx, web/app/features/article/LikeContent.tsx, web/app/features/error-boundary/ErrorPage.tsx, web/app/features/header/Header.tsx, web/app/features/jump-to-content/JumpToContent.tsx, web/app/hooks/useBreadcrumbs.ts, web/app/portable-text/Components.tsx, web/app/routes/arkiv.tsx, web/app/routes/forfatter.$name.tsx, web/utils/analytics.ts, web/utils/sanity/queries/postQueries.ts, web/utils/sanity/types/sanity.types.ts
Denne PRen fikser litt småtteri her og der.
MEN den gjør én ting: Det å legge til støtte for ordentlige bilder og litt mer info på forfatter-sidene:
=> Småfiksorama

web/app/features/article/Article.tsx, web/app/features/article/LikeContent.tsx, web/app/routes/post.$year.$date.$slug.tsx, web/tailwind.config.ts, web/types/texts.d.ts
Har fikset styling på Like-knappen og Kopier URL-knappen, ref. figmaskisser.
Endringer: 
- Stylingen, obviously
- Lagt til en type for språk og for et translate-objekt. Det er en hjemmesnekra i18n, men jeg vet ikke om vi trenger så mye mer. Jeg liker at engelske artikler har alt rundt på engelsk også!
**Før:**
**Etter:**
=> Fikset styling på like og kopierknappene i artikkel

.github/workflows/playwright.yml, web/.gitignore, web/package-lock.json, web/package.json, web/playwright.config.ts, web/tests/home.spec.ts
Denne pull requesten legger til støtte for ende-til-ende tester via [Playwright](https://playwright.dev/), og lager én test som sjekker at hovedflyten (forside, datoside og innholdsside) fungerer.
Har også satt opp en github action som skal kjøre denne på hver PR.
=> Sett opp ende-til-ende tester

web/app/features/article/Article.tsx, web/tailwind.config.ts
Lagt til taggen "Del av en artikkelserie" over tittel. Vises ikke på mobil
Før:
Etter:
=> Lagt til tag som viser at artikkel er del av en serie

web/app/components/DoorSign.tsx, web/app/features/article/RelatedPostLayout.tsx, web/app/routes/post.$year.$date.$slug.tsx, web/package-lock.json, web/package.json, web/utils/date.ts, web/utils/security.ts
💳 Lenke til [Notionkort](https://www.notion.so/bekks/Hente-relevante-innlegg-fra-algolia-1596bd30854180bb9f9acc5ade2ddd8e?pvs=4)
🐛 Type oppgave: brukerhistorie
🥅 Mål med PRen: vise relaterte innlegg
🆕 Endring: 
- implementert algolia _related products_
- enkel design i første omgang før vi implementerer Rubens design
Sjekk i preview at det funker på ulike artikler 🙏🏻
**Etter:**
=> ✨ Vise relaterte innlegg

web/app/portable-text/CodeBlock.tsx
Denne PRen legger til en rekke kodehighlighting-språk, som fikser endel 500-feil for oss på gamle artikler.
=> Legg til resterende språk

web/app/root.tsx
Denne PRen fikser en bug med caching, som gjorde at vi ikke satt caching på den måten vi trodde.
=> Legg til caching på kategorisiden

web/app/routes/post.$year.$date.$slug.tsx
Filtrer ut drafts fra relaterte artikler. Vi ser på bl.a. https://bekk.christmas/post/2024/17/hvordan-10-prosent-av-brukerne-plutselig-ble-stengt-ute-fra-bilhold at relatert innhold kræsjer. Ved å undersøke litt nøyere, ser vi at det skjer fordi vi antar at det er en slug satt. Det gir jo mening fordi slug er påkrevd. Men ved å undersøke nøyere, så så jeg at de anbefalte artiklene hadde en _id som startet med `drafts.`, som ikke er publisert innhold. Og det er jo ikke påkrevd å fylle ut noe før man har publisert.
Denne PRen fikser ikke det underliggende problemet, men filtrerer ut relaterte artikler som har en _id som starter med `drafts.`. Det gjør at det ser litt rart ut om det ikke er noe innhold som ikke er en draft, men det får så være. 
Den faktiske fiksen blir å reimportere alt …
=> Filtrer ut drafts

web/app/routes.ts
Vi får fortsatt noen som spør om RSS-feeden vår på feed.xml. Mulig det var slik i forrige løsning, og at folk har lagret det ett eller annet sted.
Denne PRen viser RSS-feeden også på feed.xml
=> Server rss-feeden både på feed.xml og rss.xml

web/app/components/DoorSign.tsx, web/app/features/article/RelatedPostLayout.tsx, web/app/features/post-preview/PostPreview.tsx, web/app/portable-text/ImageBlock.tsx, web/app/routes/post.$year.$date.$slug.tsx
Kjørte en lighthouse test på siden vår, og fikk tilbakemelding på et par smågreier.
- Gjorde om DoorSign-komponenten slik at det semantisk sett kan være en overskrift
- Satt "Relatert innhold"-DoorSign-et til å være en h2
- Gjorde et par grå tekster litt mørkere, for å få en akseptabel kontrast
=> Fiks litt uu tjafs

web/app/portable-text/CodeBlock.tsx
Denne PRen adresserer et par smågreier jeg fant utover kvelden:
- Legge til støtte for Docker som highlighting språk
=> Litt småfiks

web/app/features/calendar/CalendarWithDoors.tsx, web/app/features/calendar/NewsletterForm.tsx, web/app/features/mini-game/Cell.tsx, web/app/features/mini-game/Game.tsx, web/app/features/mini-game/GameBoard.tsx, web/app/features/mini-game/GameHeader.tsx, web/app/routes.ts, web/app/routes/julesveiper.tsx, web/utils/analytics.ts
Brukte v0.dev til å lage en liten jule-minesveiper på 15 minutter. Trykker du på den ene gaven på års-siden, så kommer du hit :)
=> Lag et lite julespill

web/app/features/article/Article.tsx, web/app/features/calendar/BottomPlank.tsx, web/app/features/calendar/NewsletterForm.tsx
Lagt til newsletter form på artikkelsiden
- fjernet planke spesifikk styling fra newsletter form og flyttet den til planke
- lagt til newsletter form på artikkelsiden under "likte innhold"
=> Add newsletter form to article

web/app/features/header/Header.tsx, web/app/routes/arkiv.tsx
Fiksa sånn at når man er på et nytt år så vil ikke kalenderen komme opp i arkivet før man er i desember. Fiksa også strukturen inne på siden så det dynamisk vil komme flere planker + pakker når det fylles opp på eksisterende "hyller"
=> add new years to archive if in december

web/app/routes/post.$year.$date.$slug.tsx
Legger til canonical link i headeren i håp om å fikse SEO
=> add canonical tags

web/app/routes/post.$year.$date.$slug.tsx
=> Fix canonical
